<?php
/**
 * @file
 * customer.module
 */

/**
 * Implements hook_permission().
 */
function customer_permission() {
    return array(
      'submit customer' => array(
        'title' => t('Submit Customer Account'),
        'description' => t('Submit and store account customer accounts to the database.'),
      ),
      'access customer submissions' => array(
        'title' => t('View Customer submissions'),
        'description' => t('Display submitted customer accounts from the database.'),
      ),
    );
}

/**
 * Implements hook_menu().
 */
function customer_menu() {
    $items = array();

    $items['customer'] = array(
        'title' => 'New Customer',
        'type' => MENU_NORMAL_ITEM,
        'access arguments' => array('submit customer'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('customer_form')
    );

    $items['customer-submissions'] = array(
        'title' => 'Customer Submissions',
        'type' => MENU_NORMAL_ITEM,
        'access arguments' => array('access customer submissions'),
        'page callback' => 'customer_submissions',
    );

    return $items;
}

/**
 * Customer form.
 */
function customer_form($form, &$form_state) {
    $form = array();

    $form["group_1"] = array(
        '#prefix' => '<section>',
        '#suffix' =>'</section>',
    );
   
   
   $form["group_1"]['div_1'] = array(
        '#prefix' => '<div style="display:flex;flex-flow:colomn wrap;">',
        '#id'     => 'div_1',
        '#suffix' => '</div>',
    );

    $form["group_1"]['div_1']['el_1'] = array(
        '#prefix' => '<div style="margin-right:1em;">',
        '#id'     => 'el_1',
        '#suffix' => '</div>',
    );

    $form['group_1']['div_1']['el_1']['customername'] = array(
        '#type' => 'textfield',
        '#title' => t('Customer Name'),
        '#size' => 15,
        '#maxlength' => 255,
        '#required' => TRUE,
        '#default_value' => '',
    );

    $form["group_1"]['div_1']['el_2'] = array(
        '#prefix' => '<div style="margin-right:1em;">',
        '#id'     => 'el_1',
        '#suffix' => '</div>',
    );

    $form['group_1']['div_1']['el_2']['customeremail'] = array(
        '#type' => 'textfield',
        '#title' => t('Customer Email'),
        '#size' => 15,
        '#maxlength' => 255,
        '#required' => TRUE,
        '#default_value' => '',
    );

    $form["group_1"]['div_1']['el_3'] = array(
        '#prefix' => '<div style="margin-right:1em;">',
        '#id'     => 'el_1',
        '#suffix' => '</div>',
    );

    $form['group_1']['div_1']['el_3']['customerphone'] = array(
        '#type' => 'textfield',
        '#attributes' => array(
            ' type' => 'number',
        ),
        '#title' => t('Customer Phone Number'),
        '#size' => 15,
        '#maxlength' => 255,
        '#required' => TRUE,
        '#default_value' => '',
    );

    $form["group_1"]['div_1']['el_4'] = array(
        '#prefix' => '<div style="margin-right:1em;">',
        '#id'     => 'el_1',
        '#suffix' => '</div>',
    );

    $form['group_1']['div_1']['el_4']['customeraddress'] = array(
        '#type' => 'textfield',
        '#title' => t('Customer Address'),
        '#size' => 15,
        '#maxlength' => 255,
        '#required' => TRUE,
        '#default_value' => '',
    );

    $form['group_2']['div_1']['el_1']['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Add Customer'),
    );

    return $form;
}

/**
 * Submit handler for the calculate_form. Inserts entry into the database
 */
function customer_form_submit($form, &$form_state) {

    $ca_id = db_insert('customer')
        ->fields(array(
            'customername' => $form_state['values']['customername'],
            'customeremail' => $form_state['values']['customeremail'],
            'customerphone' => $form_state['values']['customerphone'],
            'customeraddress' => $form_state['values']['customeraddress'],
        ))
        ->execute();

    drupal_set_message(t('Your customer form entry has been added.'));
}

/**
 * Display submitted customers from the database.
 */
function customer_submissions() {
    $query = db_select('calculate', 'c');
    $query
        ->fields('c', array('c_id', 'calcnumber', 'calctextfield', 'customer_id', 'calctext'))
        ->range(0, 50)
        ->orderBy('c.c_id', 'DESC');

    $results = $query->execute();

    $header = array(
        t('ID'), 
        t('Calculation Number'), 
        t('Calculation Textfield'), 
        t('Customer ID'), 
        t('Calculation Text')
    );
    $rows = array();

    foreach($results as $result) {
        $rows[] = array(
            check_plain($result->c_id),
            check_plain($result->calcnumber),
            check_plain($result->calctextfield),
            check_plain($result->customer_id),
            check_plain($result->calctext),
        );
    }

    return theme('table', array('header' => $header, 'rows' => $rows));
}

/**
 * Import the style for our module to use
 */
$path = drupal_get_path('module', 'customer') . '/css/MainStyle.css';
drupal_add_css($path, 'file');

?>